using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using Unity.VisualScripting;
using System.IO;
using UnityEngine.SceneManagement;
public class GameManager : MonoBehaviour
{
    public static GameManager instance;

    [Header("ç©å®¶è³‡æ–™")]
    //public InventoryManager inventoryManager;
    //public CoinManager coin;

    public ItemManager itemManager;
    public TileManager tileManager;
    public UI_Manager uiManager;
    public player_trigger player;
    public ItemData PotatoSeeds;
    public ItemData fishingFeelItem; // æŒ‡å‘ Fishing_feel çš„ itemdata

    private void Awake()
    {
        Debug.Log($"ğŸŸ¢ GameManager å•Ÿå‹•ï¼Œå ´æ™¯åç‚ºï¼š{gameObject.scene.name}");

        if (transform.root.name == "DontDestroyOnLoad")
        {
            Debug.LogWarning("é€™å€‹ GameManager æ˜¯æ®˜ç•™çš„ï¼Œæœƒè‡ªå‹•éŠ·æ¯€");
            Destroy(gameObject);
            return;
        }

        itemManager = GetComponent<ItemManager>();
        tileManager = GetComponent<TileManager>();
        uiManager = GetComponent<UI_Manager>();

        SceneManager.sceneLoaded += OnSceneLoaded;
    }

    void Start()
    {
        //é è¨­èƒŒåŒ…ç‰©å“
        InventoryManager.Instance.Add("Backpack", PotatoSeeds, 3);
        InventoryManager.Instance.Add("Backpack", fishingFeelItem, 1);
    }

    private void OnSceneLoaded(Scene scene, LoadSceneMode mode)
    {
        if (scene.name == "farm")
        {
            StartCoroutine(DelayedFarmRefresh()); //å»¶é²åˆ·æ–°
        }

        StartCoroutine(DelayedDropRefresh());
    }

    private System.Collections.IEnumerator DelayedFarmRefresh()
    {
        yield return null; // ç­‰ä¸€å¹€
        if (FarmManager.instance != null)
        {
            FarmManager.instance.LoadFarmTilesFromFile();
            Debug.Log("âœ… è‡ªå‹•åˆ·æ–°è¾²åœ°å®Œæˆ");
        }

    }

    private System.Collections.IEnumerator DelayedDropRefresh()
    {
        yield return null; // ç­‰ä¸€å¹€
        if (DropManager.instance != null)
        {
            DropManager.instance.LoadDroppedItems();
            Debug.Log("âœ… è‡ªå‹•åˆ·æ–°å ´æ™¯ç‰©ä»¶å®Œæˆ");
        }

    }


    private void OnDestroy()
    {
        SceneManager.sceneLoaded -= OnSceneLoaded;
    }
}
